name: strawberry
channels:
  - fredboudon
  - conda-forge
  - openalea

dependencies:
 - python=3.8 
 - pandas 
 - k3d 
 - jupyter 
 - voila 
 - voila-vuetify 
 - nodejs 
 - cufflinks-py 
 - ipyvuetify 
 - qgrid 
 - plotly
 - openalea.deploy 
 - openalea.mtg 
 - openalea.plantgl 
 - pip:
   - pyvis
   - pgljupyter
