name: strawberry
channels:
  - openalea3
  - conda-forge

dependencies:
 - python=3.8 
 - pandas 
 - k3d 
 - jupyter 
 - nodejs 
 - cufflinks-py 
 - ipyvuetify 
 - plotly
 - openalea.deploy 
 - openalea.mtg 
 - openalea.plantgl 
 - openpyxl
 - openalea.lpy
 - pip:
   - pyvis
   - voila
   - voila-vuetify
