name: strawberry
channels:
  - conda-forge
  - openalea3

dependencies:
 - python=3.8  
 - openalea.deploy 
 - openalea.mtg 
 - openalea.plantgl 
 - openalea.lpy
 - openpyxl
 - cufflinks-py
 - pip:
   - pyvis
   - pandas
   - k3d
   - jupyter
   - voila
   - voila-vuetify
   - nodejs
   - ipyvuetify
   - plotly
   - nbsphinx
   - sphinx-rtd-theme
   - nbsphinx-link
   - matplotlib
